name: Conditions
run-name: Run by @${{ github.actor }}
on: push
jobs:
  skip-or-run:
    if: ${{ github.actor == 'octocat' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
        if: ${{ contains(github.run_id, '1') }}